development: &defaults
  adapter: postgresql
  encoding: unicode
  database: sti_ex_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test: &test
  <<: *defaults
  database: sti_ex_test

production:
  database: sti_ex_production
  <<: *defaults
